### ISSUE TITLE
Add warning message that people will have to interact with Metamask

### ISSUE THREAD

**Issue by Deepcryptodive** [Good-Ghosting/frontend#15]
Comment Jessi: Add warning that users may see multiple Metamask pop-ups which they need to interact with. And that this might take a few minutes.

Might also be nice to add a warning that they need to use it on Kovan network! (for the prototype version)

**Comment by RachBLondon** [comment]
fixed https://github.com/Good-Ghosting/frontend/commit/e3d50a30a29873dfbaf9fe639ca84663f8392d07
