### ISSUE TITLE
Have a pop-up after users successfully deposit

### ISSUE THREAD

**Issue by Deepcryptodive** [Good-Ghosting/frontend#27]
Currently, users are often not sure whether they successfully made a deposit or not.
The page is rather static.

Suggestion: have a big animation or pop-up, once a deposit is successful.
This will be needed both after `joinGame` and `makeDeposit`.

Suggestion @RachBLondon: **Recycle the pop-up that was made for the email service?**

Ideally, you would also refresh the page after, so the Game Stats and Player Stats are updated. Thereby, increasing post-deposit engagement.

**Comment by Deepcryptodive** [comment]
https://github.com/Good-Ghosting/frontend/commit/a0c1047aae74469ec414412be0d919a593894f14 
Done

**Comment by goodghosting** [comment]
Reopening to account for when users deposit mid game. To avoid redeploying the graph sept and breaking our alpha testing app, I will do this tomorrow when the game has moved on.

**Comment by Deepcryptodive** [comment]
Cool. 
It would be nice if the page could also refresh after the user closes the pop-up. This was not the case in the latest round of user testing.

**Comment by goodghosting** [comment]
Yeah I'll make another story for that, there is something up, but can't debug properly untill this round of alpha testing is over.

This story is done now.
